#!/bin/bash
set -e
####################################
# Author: youngjack86@gmail.com
# Date: Fri Sep 21 17:56:43 CST 2018
# This script monitors jobs > 500 M
# memory and > 4 min by default.
####################################

if [ $# -eq 0 ];then
	memThres=500;
	timeThres=0.1;
elif [ $# -eq 1 -a $(echo $1 | awk '{if(/^[1-9]([0-9]+)?$/){print "1"}else{print "0"}}') -eq 1 ];then
	memThres=$1;
	timeThres=0.1;
elif [ $# -eq 2 -a $(echo $@ | awk '{if($1~/^[1-9]([0-9]+)?$/ && $2~/(^[1-9]([0-9]+)?$)|(^[0-9]+.[0-9]+$)/){print "1"}else{print "0"}}') -eq 1 ];then
	memThres=$1;
	timeThres=$2;
elif [ $# -gt 1 ];then
	echo -e "\n\033[01;42mInvalid parameter $@!\033[0;00m\n";
	memThres=500;
	timeThres=0.1;
fi
echo -e "\n\033[01;36m$(hostname) | $(ifconfig | grep 192.168 | awk '{split($2,arr,":");print arr[2]}' | head -1)\033[0;00m\t[\033[01;38m$(date)\033[0;00m]";
echo -e "\n\033[01;46mMemory\tStart_Time\t\tTotal_Run_Time\tUser_Name\tPID\tScript\033[0;00m"
for i in $(ps aux | awk '$1!~/root/ && !/\-bash/{print $1":"$2}');do
	userName=$(echo $i |cut -d ":" -f1);
	procID=$(echo $i | cut -d ":" -f2);
	neicun=$(cat /proc/$procID/status 2>/dev/null | grep VmRSS | awk '{print sprintf("%.f",$2/1E3)}END{print "0"}' | head -1);
	numLen=$(echo $neicun | wc -c);
	if [[ $userName=~/[0-9]+/ ]];then
		userName=$(getent passwd $userName | cut -d ":" -f1);
	fi
	startTime=$(ps -eo pid,lstart | grep -w $procID | awk '{sub($1" ","",$0);print $0}' | sed 's|^\s+||g');
	runTime=$(ps -eo pid,etime | grep -w $procID | awk '{len=split($NF,arr,"-");if(len==2){timeHMS=arr[2];day=arr[1]}else{timeHMS=arr[1];day=0};len2=split(timeHMS,arr2,":");if(arr2[1]~/^0/){sub("0","",arr2[1])};if(arr2[2]~/^0/){sub("0","",arr2[2])};print day*24+arr2[1]+sprintf("%.1f",arr2[2]/60)}');
	if [ $numLen -gt 2 -a $neicun -gt $memThres -a $(echo $runTime | awk -v timeThres=$timeThres '{if($1>timeThres){print "1"}else{print "0"}}') -eq 1 ];then
			echo -e "\n\033[01,35m$neicun M\033[0;00m\t[$startTime]\t\033[02;43m$runTime hrs\033[0;00m\t\033[04;31m$userName\033[0;00m\t$procID\n\n\033[01;34m"$(pmap -x $procID | head -1 | awk '{a=$0;sub($1,"",a);scripts=substr(a,4,10000);len=split(scripts,arr,/ +/);print "\\t\\t"arr[1]" "arr[2]"\\t\\\\""\\n";for(i=3;i<len;i++){if(arr[i]~/^-/ && arr[i]!~/=/){print "\\t\\t\\t"arr[i]" "arr[i+1]"\\t\\\\""\\n";i++;}else{print "\\t\\t\\t"arr[i]"\\t\\\\""\\n";}};print "\\t\\t\\t"arr[len]"\\n"}')"\033[0;00m";
	fi
done
